version: '3'

services:
  api-game-list-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=gamelistapi
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
